---
collections:
  - name: ansible.posix
    version: 1.6.2
  - name: community.general
    version: 9.5.0
  - name: kubernetes.core
    version: 5.0.0
  - name: community.routeros
    version: 3.12.1
  - name: community.sops
    version: 1.9.1
roles:
  - src: geerlingguy.pip
    version: 3.0.3
