---
collections:
  - name: ansible.posix
    version: 1.5.1
  - name: community.general
    version: 6.5.0
  - name: kubernetes.core
    version: 2.4.0
  - name: community.Routeros
    version: 2.7.0
  - name: community.sops
    version: 1.6.1
roles:
  - src: geerlingguy.pip
    version: 2.2.0
