---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 7.4.0
  - name: kubernetes.core
    version: 3.0.0
  - name: community.routeros
    version: 2.9.0
  - name: community.sops
    version: 1.6.6
roles:
  - src: geerlingguy.pip
    version: 2.2.0
