---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 8.2.0
  - name: kubernetes.core
    version: 3.0.0
  - name: community.routeros
    version: 2.10.0
  - name: community.sops
    version: 1.6.7
roles:
  - src: geerlingguy.pip
    version: 3.0.1
