---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 9.1.0
  - name: kubernetes.core
    version: 5.0.0
  - name: community.routeros
    version: 2.15.0
  - name: community.sops
    version: 1.6.7
roles:
  - src: geerlingguy.pip
    version: 3.0.3
