---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 11.4.0
  - name: kubernetes.core
    version: 6.2.0
  - name: community.routeros
    version: 3.12.1
  - name: community.sops
    version: 2.2.7
roles:
  - src: geerlingguy.pip
    version: 3.1.0
