networks:
  - name: wired
    cidr: 172.16.116.0/24
  - name: wifi
    cidr: 172.16.115.0/24
  - name: iot
    cidr: 172.16.114.0/24
  - name: mgmt
    cidr: 172.16.113.0/24
  - name: servers
    cidr: 172.16.112.0/24
